pipeline:
  identifier: Build_SudheerNunna123_maven_web_app_1743767074007
  name: Build maven-web-app
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: SudheerNunna123/maven-web-app
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: maven_build
                  name: Build WAR File
                  type: Run
                  spec:
                    shell: Sh
                    image: maven:3.8-jdk-11
                    connectorRef: account.harnessImage
                    command: |
                      mvn clean package
                      echo "Listing files in target directory:"
                      ls -l target
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: sudheer123143/maven-web-app
                    tags:
                      - <+codebase.tag>
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
